server:
  port : 8088

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:persondb
    username: n0rth
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
